name: CI/CD

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         
     - uses: actions/cache@v3
       with:
         path: |
           venv
           ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-

     - name: Install dependencies
       run: |
         python -m venv venv
         source venv/bin/activate
         pip install -r requirements.txt
         
     - name: Install Playwright browsers
       run: |
        source venv/bin/activate
         playwright install --with-deps

     - name: Run tests
       run: |
         source venv/bin/activate
         pytest tests/unit/ --cov=src --junitxml=test-results/junit.xml
         pytest tests/integration/
        

 security:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4          
 deploy:
   needs: security
   if: github.ref == 'refs/heads/main'
   runs-on: ubuntu-latest
   environment: production
   steps:
     - uses: actions/checkout@v4
    