name: CI - FastAPI Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python (match your local version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # Changed from 3.11 to match your local setup

      # 3. Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Install Playwright browsers (FIXED - use Python playwright, not npm)
      - name: Install Playwright browsers
        run: |
          playwright install chromium --with-deps

      # 6. Run pytest (fail fast if any test fails)
      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings